-- Wipe and re-seed the Jev validation examples.
DELETE FROM jev_prompts;

INSERT INTO jev_prompts (flow, message, expected_result) VALUES
('classification', 'Salva o telefone do João: (11) 91234-5678', 'contact:add'),
('classification', 'Adiciona o email da Maria: maria@exemplo.com', 'contact:add'),
('classification', 'Quero o contato do Pedro, me passa o número dele', 'contact:require'),
('classification', 'Me lembra de pagar a conta de luz amanhã', 'notes:add'),
('classification', 'Quanto gastei com mercado esse mês?', 'finance:require'),
('classification', 'Agenda reunião com o time às 14h', 'schedule:add'),
('classification', 'Que horas é minha consulta na sexta?', 'schedule:require'),
('classification', 'Anota que preciso comprar pão', 'notes:add'),
('classification', 'Me mostra minhas anotações sobre o projeto', 'notes:require'),
('classification', 'Isso não é nada importante', 'other:add'),
('name', 'Salva o contato do João da Silva, telefone (11) 91234-5678', 'João da Silva'),
('name', 'Adiciona Maria Clara Oliveira ao catálogo', 'Maria Clara Oliveira'),
('name', 'Cadastra o Pedro Henrique Santos', 'Pedro Henrique Santos'),
('name', 'Guarda o número da Ana Beatriz', 'Ana Beatriz'),
('name', 'Contato do José Carlos de Souza', 'José Carlos de Souza'),
('name', 'Salva a Ana Paula, email ana@exemplo.com', 'Ana Paula'),
('note', 'Anota que preciso comprar pão', 'note'),
('note', 'Me lembra de pagar a conta de luz dia 10', 'reminder'),
('note', 'Lembrete: consulta com o dentista 10/05/2026 às 14h', 'reminder'),
('note', 'Tarefas: comprar pão, leite e ovos', 'todo'),
('note', 'Preciso fazer: 1. revisar contrato 2. enviar relatório', 'todo'),
('note', 'Guarda essa ideia: mudar o nome do projeto para atlas', 'note'),
('note', 'Me lembra de comprar pão', 'note'),
('note', 'Anota a ideia de criar um app de receitas', 'note'),
('note', 'Registra que o projeto atlas está atrasado', 'note'),
('note', 'Guarda isso: comprar presente para a mãe', 'note'),
('note', 'Me lembra amanhã de levar o lixo', 'reminder'),
('note', 'Lembrete dia 15 para pagar o aluguel', 'reminder'),
('note', 'Não posso esquecer da consulta dia 20', 'reminder'),
('note', 'comprar pão, leite e ovos', 'todo'),
('note', 'Lista: lavar o carro, limpar a casa, pagar as contas', 'todo'),
('note', '1. revisar contrato 2. enviar relatório 3. ligar para o cliente', 'todo'),
('note', 'Comprar: arroz, feijão, alho e 2 cenouras', 'todo'),
('note', 'Lista do mercado: óleo, açúcar e café', 'todo'),
('note', 'Pendências: ligar para o banco, conferir o extrato e pagar a fatura', 'todo'),
    ('finance', 'Gastei 50 reais no supermercado hoje', 'compra'),
    ('finance', 'Comprei pão, leite e ovos no mercado', 'compra'),
    ('finance', 'Paguei a conta de luz, 250 reais', 'pagamento'),
    ('finance', 'Recebi 500 reais do MoviePy, versão', 'recebimento'),
    ('finance', 'Vendi meu notebook por 800 reais', 'venda'),
    ('finance', 'Transferi 200 reais para a conta da minha mãe', 'transferencia'),
    ('finance', 'Cabo de celular 20 reais hoje no cartão', 'compra'),
    ('finance', 'Aluguel 1200 reais', 'pagamento'),
    ('finance', 'Café na padaria 8 reais', 'compra');