// Package main is the REST entrypoint (DC-009). It serves JSON only; the web
// lives in cmd/web and the terminal in cmd/cli. All three sit on internal/app.
//
//	@title			msg-classifier API
//	@version		v1
//	@description	REST entrypoint over the message classifier core. POST /api/v1/messages runs the same Classify → Dispatch as the web and the CLI and answers the outcome as JSON; the browse endpoints are read-only.
//	@BasePath		/api/v1
package main

import (
	"log"

	"msg-classifier/internal/api"
	"msg-classifier/internal/app"
	"msg-classifier/internal/config"

	_ "msg-classifier/docs" // generated by swag init; its init registers the spec

	"github.com/gin-gonic/gin"
	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"
)

func main() {
	env := config.GetEnv()

	application, err := app.New(env.DBPath)
	if err != nil {
		log.Fatalf("failed to build application: %v", err)
	}

	router := gin.Default()
	v1 := router.Group("/api/v1")
	v1.POST("/messages", api.NewMessageController(application.Classifier, application.Dispatcher).ReceiveMessage)

	browse := api.NewDataController(application.Data)
	v1.GET("/contacts", browse.ListContacts)
	v1.GET("/notes", browse.ListNotes)
	v1.GET("/transactions", browse.ListTransactions)

	router.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	if err := router.Run(":" + env.ApiPort); err != nil {
		log.Fatalf("api server stopped: %v", err)
	}
}
